### PR TITLE
Install realpath

### PR DESCRIPTION
**Pull request by kavedder**

### CODE REVIEW

**Comment by kavedder** [comment]
Thanks, I _always_ forget that step.

**Comment by michaelb990** [comment]
:shipit:

**Comment by RoboticCheese** [comment]
This cookbook doesn't auto-release (yet) so the version bump isn't necessary.

The build is also currently broken and probably going to fail. I'm working on it.

**Comment by kavedder** [comment]
How do you feel about me merging this change @RoboticCheese ?

**Pull request closed without merging**
